version: "3.8"

services:
  chromadb:
    image: chromadb/chroma:1.0.13.dev120
    hostname: chromadb.ots.com
    restart: unless-stopped
    volumes:
      - ./persist/chromadb:/data

  redis:
    image: bitnami/redis:8.0.2
    hostname: redis.ots.com
    restart: unless-stopped
    ports:
      - "6400:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./persist/redis:/bitnami/redis/data

  scrape:
    image: optisign_poc:v1
    hostname: scrape.ots.com
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    command: npx nodemon src/scrape.ts
    env_file:
      - .env.scrape
    volumes:
      - ./node_modules:/app/node_modules
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    depends_on:
      - chromadb
      - redis

  api:
    image: optisign_poc:v1
    hostname: api.ots.com
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8135:3000"
    command: npx nodemon src/app.ts
    env_file:
      - .env.api
    volumes:
      - ./node_modules:/app/node_modules
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    depends_on:
      - chromadb
