version: "3.8"

services:
  chromadb:
    image: chromadb/chroma:1.0.13.dev120
    hostname: chromadb.ots.com
    restart: unless-stopped
    volumes:
      - ./persist/chromadb:/data

  scrape:
    image: optisign_poc:v1
    hostname: scrape.ots.com
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: npx nodemon src/scrape.ts
    env_file:
      - .env.scrape
    volumes:
      - ./out:/app/out
      - ./persist/chroma.db:/app/persist/chroma.db
      #
      - ./node_modules:/app/node_modules
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json

  api:
    image: optisign_poc:v1
    hostname: api.ots.com
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: npx nodemon src/app.ts
    env_file:
      - .env.api
    volumes:
      - ./out:/app/out
      - ./persist/chroma.db:/app/persist/chroma.db
      #
      - ./node_modules:/app/node_modules
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json

  redis:
    image: bitnami/redis:8.0.2
    hostname: redis.ots.com
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./persist/redis:/bitnami/redis/data
