FROM node:22.0.0-alpine AS build-stage
WORKDIR /app
COPY --chown=node:node ./package*.json ./tsconfig.json /app/
RUN npm i
COPY --chown=node:node ./src /app/src
RUN npx tsc

FROM node:22.0.0-alpine AS production-stage
WORKDIR /app
COPY --chown=node:node ./package*.json /app/
RUN npm i --omit=dev
COPY --chown=node:node --from=build-stage /app/dist /app/dist
USER node
CMD [ "node", "dist/app.js" ]